import { LogOut } from "lucide-react";
import { Link, NavLink } from "react-router-dom";
import { useAuth } from "../auth/AuthContext";

function RefereeLayout({ title, eyebrow, description, children, actions }) {
  const { signOut, user } = useAuth();
  return <main className="admin-page referee-page" aria-label={title}><section className="admin-shell"><aside className="admin-sidebar referee-sidebar"><div className="admin-brand"><Link className="admin-brand__link brand" to="/" aria-label="Horse racing home"><span className="brand-mark">HR</span><span className="brand-text"><strong>horse</strong><span>racing</span></span></Link><div className="admin-badge referee-badge">REFEREE</div></div><div className="admin-sidebar__section"><p className="admin-sidebar__eyebrow">Race Operations</p><nav className="admin-nav" aria-label="Referee sections"><NavLink to="/referee" end className={({ isActive }) => isActive ? "active" : ""}>Dashboard</NavLink><NavLink to="/referee/races" className={({ isActive }) => isActive ? "active" : ""}>My Races</NavLink></nav></div><div className="admin-sidebar__panel referee-sidebar__panel"><p className="admin-sidebar__eyebrow">Authority</p><h3>Assigned race official</h3><p>Record checks, incidents, draft results, and reports. Admin confirms and publishes official results.</p></div><div className="admin-sidebar__panel referee-sidebar__panel referee-sidebar__panel--rules"><p className="admin-sidebar__eyebrow">Restrictions</p><ul className="referee-restriction-list"><li>No race lifecycle controls</li><li>No schedule changes</li><li>No participant assignments</li><li>No result publication</li></ul></div><div className="admin-user-row"><div className="admin-user-avatar referee-avatar" aria-hidden="true">RF</div><div className="admin-user-info"><span className="admin-user-name">{user?.full_name || "Race Referee"}</span><span className="admin-user-role">Race Referee</span></div><button className="admin-logout-btn" type="button" title="Sign out" aria-label="Sign out" onClick={signOut}><LogOut aria-hidden="true" size={16} /></button></div></aside><section className="admin-content"><header className="admin-header"><div><p className="admin-header__eyebrow">{eyebrow}</p><h1>{title}</h1><p className="admin-header__description">{description}</p></div><div className="admin-header__actions">{actions}</div></header>{children}</section></section></main>;
}

export default RefereeLayout;
