// ── Mock data for Referee module ──────────────────────────────────────────────

export const RACE_STATUSES = {
  UPCOMING: "Upcoming",
  INSPECTION_PENDING: "Inspection Pending",
  READY: "Ready",
  IN_PROGRESS: "In Progress",
  FINISHED: "Finished",
  PUBLISHED: "Published",
};

export const RESULT_STATUSES = {
  DRAFT: "Draft",
  CONFIRMED: "Confirmed",
  PUBLISHED: "Published",
};

export const VIOLATION_TYPES = [
  "Dangerous Riding",
  "Lane Violation",
  "False Start",
  "Equipment Violation",
  "Unsportsmanlike Conduct",
];

export const PENALTY_TYPES = ["Warning", "Time Penalty", "Disqualification"];

export const assignedRaces = [
  {
    id: "R-01",
    name: "Spring Cup — Heat 1",
    tournament: "Spring Cup 2026",
    track: "Grandstand District",
    date: "2026-06-08",
    startTime: "08:30",
    status: RACE_STATUSES.INSPECTION_PENDING,
    participants: [
      {
        horseId: "H-001",
        horseName: "Storm Arrow",
        breed: "Thoroughbred",
        age: 4,
        weight: 512,
        owner: "Minh Le",
        jockeyId: "J-11",
        jockeyName: "Anh Khoa",
        jockeyLicense: "VN-J-2024-011",
        lane: 1,
        horseInspection: null,
        jockeyInspection: null,
      },
      {
        horseId: "H-002",
        horseName: "Blue Horizon",
        breed: "Warmblood",
        age: 5,
        weight: 534,
        owner: "Nhan Tran",
        jockeyId: "J-12",
        jockeyName: "Le Nam",
        jockeyLicense: "VN-J-2024-012",
        lane: 2,
        horseInspection: null,
        jockeyInspection: null,
      },
      {
        horseId: "H-004",
        horseName: "Night Sprint",
        breed: "Thoroughbred",
        age: 6,
        weight: 521,
        owner: "Hoang Anh",
        jockeyId: "J-14",
        jockeyName: "Duc Huy",
        jockeyLicense: "VN-J-2024-014",
        lane: 3,
        horseInspection: null,
        jockeyInspection: null,
      },
    ],
    violations: [],
    result: null,
    resultStatus: null,
    raceTimer: 0,
    monitorNotes: [],
  },
  {
    id: "R-02",
    name: "Spring Cup — Heat 2",
    tournament: "Spring Cup 2026",
    track: "Grandstand District",
    date: "2026-06-08",
    startTime: "10:00",
    status: RACE_STATUSES.READY,
    participants: [
      {
        horseId: "H-003",
        horseName: "Golden Mane",
        breed: "Arabian",
        age: 3,
        weight: 498,
        owner: "Cam Tu",
        jockeyId: "J-13",
        jockeyName: "Phuong Vy",
        jockeyLicense: "VN-J-2024-013",
        lane: 1,
        horseInspection: { status: "Approved", notes: "All checks passed." },
        jockeyInspection: { status: "Approved", notes: "License valid." },
      },
      {
        horseId: "H-005",
        horseName: "Silver Wind",
        breed: "Warmblood",
        age: 4,
        weight: 509,
        owner: "Bao Nguyen",
        jockeyId: "J-12",
        jockeyName: "Le Nam",
        jockeyLicense: "VN-J-2024-012",
        lane: 2,
        horseInspection: { status: "Approved", notes: "Weight within range." },
        jockeyInspection: { status: "Approved", notes: "No suspension on record." },
      },
    ],
    violations: [],
    result: null,
    resultStatus: null,
    raceTimer: 0,
    monitorNotes: [],
  },
  {
    id: "R-03",
    name: "Spring Cup — Semi-Final",
    tournament: "Spring Cup 2026",
    track: "North Track",
    date: "2026-06-10",
    startTime: "14:00",
    status: RACE_STATUSES.UPCOMING,
    participants: [
      {
        horseId: "H-001",
        horseName: "Storm Arrow",
        breed: "Thoroughbred",
        age: 4,
        weight: 512,
        owner: "Minh Le",
        jockeyId: "J-11",
        jockeyName: "Anh Khoa",
        jockeyLicense: "VN-J-2024-011",
        lane: 1,
        horseInspection: null,
        jockeyInspection: null,
      },
      {
        horseId: "H-003",
        horseName: "Golden Mane",
        breed: "Arabian",
        age: 3,
        weight: 498,
        owner: "Cam Tu",
        jockeyId: "J-13",
        jockeyName: "Phuong Vy",
        jockeyLicense: "VN-J-2024-013",
        lane: 2,
        horseInspection: null,
        jockeyInspection: null,
      },
    ],
    violations: [],
    result: null,
    resultStatus: null,
    raceTimer: 0,
    monitorNotes: [],
  },
  {
    id: "R-04",
    name: "Spring Cup — Final",
    tournament: "Spring Cup 2026",
    track: "West Arena",
    date: "2026-06-12",
    startTime: "15:00",
    status: RACE_STATUSES.PUBLISHED,
    participants: [
      {
        horseId: "H-004",
        horseName: "Night Sprint",
        breed: "Thoroughbred",
        age: 6,
        weight: 521,
        owner: "Hoang Anh",
        jockeyId: "J-14",
        jockeyName: "Duc Huy",
        jockeyLicense: "VN-J-2024-014",
        lane: 1,
        horseInspection: { status: "Approved", notes: "Peak condition." },
        jockeyInspection: { status: "Approved", notes: "Cleared by medics." },
      },
      {
        horseId: "H-001",
        horseName: "Storm Arrow",
        breed: "Thoroughbred",
        age: 4,
        weight: 512,
        owner: "Minh Le",
        jockeyId: "J-11",
        jockeyName: "Anh Khoa",
        jockeyLicense: "VN-J-2024-011",
        lane: 2,
        horseInspection: { status: "Approved", notes: "No issues found." },
        jockeyInspection: { status: "Approved", notes: "License valid until Dec 2026." },
      },
    ],
    violations: [
      {
        id: "V-001",
        type: "Lane Violation",
        subject: "Jockey",
        subjectName: "Duc Huy",
        penalty: "Warning",
        description: "Slight lane drift at turn 2.",
        timestamp: "2026-06-12T15:14:00Z",
      },
    ],
    result: [
      { position: 1, horseId: "H-004", horseName: "Night Sprint", jockeyName: "Duc Huy", finishTime: "1:38.02", penaltyApplied: false },
      { position: 2, horseId: "H-001", horseName: "Storm Arrow", jockeyName: "Anh Khoa", finishTime: "1:39.14", penaltyApplied: false },
    ],
    resultStatus: RESULT_STATUSES.PUBLISHED,
    raceTimer: 0,
    monitorNotes: ["Race started cleanly.", "Lane drift noted at turn 2 — warning issued."],
  },
];

export const auditLog = [
  { id: "AL-001", userId: "RF-01", raceId: "R-04", action: "Result Confirmed", entityType: "Race", entityId: "R-04", timestamp: "2026-06-12T16:02:11Z" },
  { id: "AL-002", userId: "RF-01", raceId: "R-04", action: "Violation Created", entityType: "Violation", entityId: "V-001", timestamp: "2026-06-12T15:14:05Z" },
  { id: "AL-003", userId: "RF-01", raceId: "R-04", action: "Horse Approved", entityType: "Horse", entityId: "H-004", timestamp: "2026-06-12T14:30:00Z" },
];
